title: AzerothCore Wiki
description: Wiki repository of AzerothCore project
show_downloads: true
git_branch: master
logo_url: http://www.azerothcore.org/images/logo.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: true
custom_footer: false
include: [wiki/_Sidebar.md,wiki/_Footer.md]
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
